import React, { useMemo, useState } from 'react';
import { budgets } from '../data/planData';
import { uid } from '../lib/workPlan';
import { Card, Empty, Modal } from './Common';

const blank=()=>({id:uid('expense'),date:new Date().toISOString().slice(0,10),amount:'',currency:'CNY',cnyEquivalent:'',vendor:'',purpose:'',owner:'公司',phase:'phase-1',payment:'',receipt:false,reimbursement:'计入公司'});
export default function ExpenseLedger({expenses,setExpenses}) {
  const [editing,setEditing]=useState(null);
  const totals=useMemo(()=>expenses.reduce((a,e)=>{a[e.currency]=(a[e.currency]||0)+Number(e.amount||0);a.cny+=(e.currency==='CNY'?Number(e.amount||0):Number(e.cnyEquivalent||0));return a},{cny:0}),[expenses]);
  const save=e=>{e.preventDefault();const item={...editing,amount:Number(editing.amount),cnyEquivalent:Number(editing.cnyEquivalent||0)};setExpenses(v=>v.some(x=>x.id===item.id)?v.map(x=>x.id===item.id?item:x):[item,...v]);setEditing(null)};
  return <Card className="workbench-card"><div className="workbench-head"><div><span className="kicker">本地财务工作台</span><h3>费用与现金记录</h3></div><button className="primary" onClick={()=>setEditing(blank())}>记录费用</button></div>
    <div className="mini-stats"><div><span>人民币等值合计</span><strong>¥ {totals.cny.toLocaleString()}</strong></div>{Object.entries(totals).filter(([k])=>k!=='cny').map(([k,v])=><div key={k}><span>{k}原币合计</span><strong>{v.toLocaleString()}</strong></div>)}</div>
    {!expenses.length?<Empty>尚无费用。个人生活支出和公司经营支出必须分别记录。</Empty>:<div className="table-scroll"><table><thead><tr><th>日期</th><th>金额</th><th>用途 / 对象</th><th>归属</th><th>预算阶段</th><th>票据</th><th></th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.date}</td><td><strong>{e.currency} {Number(e.amount).toLocaleString()}</strong>{e.currency!=='CNY'&&<small>CNY等值 {Number(e.cnyEquivalent||0).toLocaleString()}</small>}</td><td>{e.purpose}<small>{e.vendor}</small></td><td>{e.owner}<small>{e.reimbursement}</small></td><td>{budgets.find(b=>b.id===e.phase)?.name}</td><td>{e.receipt?'已保存':'待补'}</td><td className="row-actions"><button onClick={()=>setEditing({...e})}>编辑</button><button className="danger-link" onClick={()=>confirm('删除这笔费用记录？')&&setExpenses(v=>v.filter(x=>x.id!==e.id))}>删除</button></td></tr>)}</tbody></table></div>}
    {editing&&<Modal title="费用记录" onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={save}><label>日期*<input required type="date" value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label><label>金额*<input required min="0" step="0.01" type="number" value={editing.amount} onChange={e=>setEditing({...editing,amount:e.target.value})}/></label><label>币种<select value={editing.currency} onChange={e=>setEditing({...editing,currency:e.target.value})}><option>CNY</option><option>USD</option><option>CAD</option><option>HKD</option><option>其他</option></select></label>{editing.currency!=='CNY'&&<label>人民币等值（自行填写）<input min="0" step="0.01" type="number" value={editing.cnyEquivalent} onChange={e=>setEditing({...editing,cnyEquivalent:e.target.value})}/></label>}<label>支出对象<input value={editing.vendor} onChange={e=>setEditing({...editing,vendor:e.target.value})}/></label><label>用途*<input required value={editing.purpose} onChange={e=>setEditing({...editing,purpose:e.target.value})}/></label><label>个人或公司<select value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}><option>公司</option><option>个人</option></select></label><label>预算阶段<select value={editing.phase} onChange={e=>setEditing({...editing,phase:e.target.value})}>{budgets.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>付款方式<input value={editing.payment} onChange={e=>setEditing({...editing,payment:e.target.value})}/></label><label>报销/入账<select value={editing.reimbursement} onChange={e=>setEditing({...editing,reimbursement:e.target.value})}><option>计入公司</option><option>待报销</option><option>个人承担</option><option>待确认</option></select></label><label className="check-line full"><input type="checkbox" checked={editing.receipt} onChange={e=>setEditing({...editing,receipt:e.target.checked})}/>票据已保存</label><div className="form-actions full"><button type="button" onClick={()=>setEditing(null)}>取消</button><button className="primary">保存费用</button></div></form></Modal>}
  </Card>;
}
