import React, { useMemo, useState } from 'react';
import { capabilityNames, entrepreneurBehaviors, learningPriorities, learningPriorityLabels, learningResourceTypes, learningStatuses, learningTimeline } from '../data/planData';
import { uid } from '../lib/workPlan';
import { Card, Empty, Modal, Tag } from './Common';

const resourceBlank=()=>({id:uid('learning'),name:'',type:learningResourceTypes[0],topic:'',platform:'',hours:'',priority:'当前业务需要',status:'待评估',role:'候选资源',why:'',businessProblem:'',startDate:'',targetDate:'',completedDate:'',notes:'',application:'',action:'',effect:'',createdAt:new Date().toISOString()});

function ResourceLibrary({resources,setResources}) {
  const [editing,setEditing]=useState(null),[status,setStatus]=useState('全部');
  const visible=resources.filter(r=>status==='全部'||r.status===status);
  const save=e=>{e.preventDefault();if(editing.status==='学习中'){const conflict=resources.find(r=>r.id!==editing.id&&r.status==='学习中');if(conflict){alert(`当前知识缺口已由“${conflict.name}”处理。请先完成或暂停，再启动新资源。`);return}}const item={...editing,role:'主要课程',updatedAt:new Date().toISOString()};setResources(v=>v.some(x=>x.id===item.id)?v.map(x=>x.id===item.id?item:x):[item,...v]);setEditing(null)};
  const activeMain=resources.find(r=>r.status==='学习中');
  return <Card className="learning-workbench"><div className="workbench-head"><div><span className="kicker">当前只保留一个知识缺口</span><h3>学习资源库</h3></div><button className="primary" onClick={()=>setEditing(resourceBlank())}>新增学习资源</button></div>
    <div className="learning-capacity"><div><span>当前学习资源</span><strong>{activeMain?.name||'未设置'}</strong></div><div><span>要解决的业务问题</span><strong>{activeMain?.businessProblem||'未设置'}</strong></div><p>优先问客户、供应商或专家；没有完成或暂停当前资源前，不启动新课程。</p></div>
    <div className="filter-row compact-filter"><div>{['全部',...learningStatuses].map(x=><button className={status===x?'active':''} onClick={()=>setStatus(x)} key={x}>{x}</button>)}</div></div>
    {!visible.length?<Empty>{resources.length?'当前筛选下没有资源。':'资源库为空。不要批量收藏课程；只添加正在解决真实业务问题的资源。'}</Empty>:<div className="resource-list">{visible.map(r=><article key={r.id}><div className="resource-main"><div><Tag tone={r.priority==='当前业务需要'?'gold':'muted'}>{r.priority}</Tag><Tag tone={r.status==='已转化为行动'?'green':r.status==='学习中'?'gold':'muted'}>{r.status}</Tag><h4>{r.name}</h4><p>{r.businessProblem||'尚未写明要解决的业务问题'}</p></div><div className="resource-meta"><span>{r.type} · {r.platform||'来源待确认'}</span><span>{r.hours||'TBD'} 小时 · {r.role}</span><span>目标：{r.targetDate||'TBD'}</span></div></div><div className="resource-result"><strong>拟应用</strong><span>{r.application||'尚未设置'}</span><strong>实际行动</strong><span>{r.action||'尚未行动'}</span></div><div className="row-actions"><button onClick={()=>setEditing({...r})}>编辑 / 更新转化</button><button className="danger-link" onClick={()=>confirm(`删除“${r.name}”？`)&&setResources(v=>v.filter(x=>x.id!==r.id))}>删除</button></div></article>)}</div>}
    {editing&&<Modal title={resources.some(r=>r.id===editing.id)?'更新学习资源与转化':'评估一个学习资源'} onClose={()=>setEditing(null)}><form className="form-grid resource-form" onSubmit={save}><label>资源名称*<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>类型<select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value})}>{learningResourceTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>学习主题*<input required value={editing.topic} onChange={e=>setEditing({...editing,topic:e.target.value})}/></label><label>来源平台<input value={editing.platform} onChange={e=>setEditing({...editing,platform:e.target.value})}/></label><label>预计时间（小时）<input min="0" step="0.5" type="number" value={editing.hours} onChange={e=>setEditing({...editing,hours:e.target.value})}/></label><label>优先级<select value={editing.priority} onChange={e=>setEditing({...editing,priority:e.target.value})}>{learningPriorityLabels.map(x=><option key={x}>{x}</option>)}</select></label><label>当前状态<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}>{learningStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label className="full">为什么学习<textarea required value={editing.why} onChange={e=>setEditing({...editing,why:e.target.value})} placeholder="为什么是现在，而不是以后？"/></label><label className="full">需要解决的业务问题*<textarea required value={editing.businessProblem} onChange={e=>setEditing({...editing,businessProblem:e.target.value})} placeholder="先定义问题，不要先定义课程。"/></label><label>开始日期<input type="date" value={editing.startDate} onChange={e=>setEditing({...editing,startDate:e.target.value})}/></label><label>目标完成日期<input type="date" value={editing.targetDate} onChange={e=>setEditing({...editing,targetDate:e.target.value})}/></label><label>实际完成日期<input type="date" value={editing.completedDate} onChange={e=>setEditing({...editing,completedDate:e.target.value})}/></label><label>学习效果<input value={editing.effect} onChange={e=>setEditing({...editing,effect:e.target.value})} placeholder="有效 / 部分有效 / 无效及证据"/></label><label>关键笔记（最多五条）<textarea value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><label>可应用到公司的内容<textarea value={editing.application} onChange={e=>setEditing({...editing,application:e.target.value})}/></label><label className="full">已采取的实际行动<textarea value={editing.action} onChange={e=>setEditing({...editing,action:e.target.value})} placeholder="没有行动时保持为空，不把笔记当成果。"/></label><div className="form-actions full"><button type="button" onClick={()=>setEditing(null)}>取消</button><button className="primary">保存资源</button></div></form></Modal>}
  </Card>;
}

const emptyCapability=()=>({score:1,evidence:'',change:'',problem:'',practice:'',help:'不需要'});
function CapabilityDashboard({reviews,setReviews}) {
  const now=new Date(),defaultQuarter=`${now.getFullYear()}-Q${Math.floor(now.getMonth()/3)+1}`;
  const [quarter,setQuarter]=useState(defaultQuarter),[editing,setEditing]=useState(null);
  const quarterData=reviews[quarter]||{};
  const quarterOptions=useMemo(()=>Array.from({length:12},(_,i)=>{const n=Number(quarter.slice(-1))-i,y=Number(quarter.slice(0,4))+Math.floor((n-1)/4),q=((n-1)%4+4)%4+1;return `${y}-Q${q}`}),[quarter]);
  const previous=useMemo(()=>reviews[quarterOptions[1]]||{},[quarterOptions,reviews]);
  const average=capabilityNames.reduce((sum,n)=>sum+Number(quarterData[n]?.score||0),0)/capabilityNames.length;
  const save=e=>{e.preventDefault();setReviews(v=>({...v,[quarter]:{...v[quarter],[editing.name]:{...editing.data,updatedAt:new Date().toISOString()}}}));setEditing(null)};
  return <div className="capability-block"><div className="capability-head"><div><span className="kicker">每季度用行为证据评分</span><h3>创业者能力仪表板</h3></div><label>评估季度<select value={quarter} onChange={e=>setQuarter(e.target.value)}>{quarterOptions.map(x=><option key={x}>{x}</option>)}</select></label><div className="average-score"><span>平均分</span><strong>{average?average.toFixed(1):'—'} / 5</strong></div></div><div className="capability-grid">{capabilityNames.map(name=>{const data=quarterData[name],prev=previous[name]?.score,delta=data&&prev?data.score-prev:null;return <Card key={name} className="capability-card"><div className="capability-title"><h4>{name}</h4><strong>{data?.score||'—'}<small>/5</small></strong></div><div className="ability-bar"><span style={{width:`${(data?.score||0)*20}%`}} /></div><p><b>行为证据</b>{data?.evidence||'尚未记录，分数必须有证据支持。'}</p>{data&&<><p><b>相比上季度</b>{data.change||'未补充变化说明'}</p><p><b>最大问题</b>{data.problem}</p><p><b>下季度练习</b>{data.practice}</p><small>{delta===null?'暂无上季度分数':`分数变化 ${delta>0?'+':''}${delta}`} · {data.help}</small></>}<button className="secondary" onClick={()=>setEditing({name,data:{...emptyCapability(),...data}})}>{data?'更新证据':'开始评估'}</button></Card>})}</div>
    {editing&&<Modal title={`${quarter} · ${editing.name}`} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={save}><label>当前评分*<select value={editing.data.score} onChange={e=>setEditing({...editing,data:{...editing.data,score:Number(e.target.value)}})}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}分</option>)}</select></label><label>相比上季度变化说明<input value={editing.data.change} onChange={e=>setEditing({...editing,data:{...editing.data,change:e.target.value}})} placeholder="进步、退步或无变化的原因"/></label><label className="full">本季度行为证据*<textarea required value={editing.data.evidence} onChange={e=>setEditing({...editing,data:{...editing.data,evidence:e.target.value}})} placeholder="次数、结果、错误或客户反馈；不能只写主观感受。"/></label><label>当前最大问题*<textarea required value={editing.data.problem} onChange={e=>setEditing({...editing,data:{...editing.data,problem:e.target.value}})}/></label><label>下季度具体练习*<textarea required value={editing.data.practice} onChange={e=>setEditing({...editing,data:{...editing.data,practice:e.target.value}})} placeholder="可观察、可统计的行为"/></label><label className="full">需要什么帮助<select value={editing.data.help} onChange={e=>setEditing({...editing,data:{...editing.data,help:e.target.value}})}><option>不需要</option><option>课程</option><option>导师/专业人士</option><option>真实项目练习</option></select></label><div className="form-actions full"><button type="button" onClick={()=>setEditing(null)}>取消</button><button className="primary">保存评分与证据</button></div></form></Modal>}
  </div>;
}

export default function LearningDevelopment({resources,setResources,reviews,setReviews}) {
  const [priority,setPriority]=useState('A');
  const selected=learningPriorities.find(x=>x.id===priority);
  return <>
    <div className="learning-manifesto"><span>个人学习原则</span><blockquote>学习的价值不在于完成多少课程，而在于是否改善了下一次客户沟通、商业判断、管理流程和资金决策。</blockquote><strong>当前最重要的学习资源，是客户、供应商、设备和真实经营结果。网课用于补充框架，不能代替市场行动。</strong></div>
    <div className="learning-principles">{['学习不能替代客户开发','当前只保留一个知识缺口','优先问客户、供应商或专家','每次学习必须产生实际输出','每周学习不超过2小时','能力评估每季度一次'].map(x=><div key={x}>{x}</div>)}</div>
    <div className="learning-subhead"><span className="kicker">2026 学习重点</span><h3>按业务紧迫度，而不是兴趣排序</h3></div><div className="priority-tabs">{learningPriorities.map(x=><button key={x.id} className={priority===x.id?'active':''} onClick={()=>setPriority(x.id)}><b>{x.id}</b><span>{x.title}</span></button>)}</div><p className="priority-note">{selected.note}</p><div className="learning-topic-grid">{selected.topics.map(t=><Card key={t.name}><h4>{t.name}</h4>{t.legal&&<Tag tone="red">需专业人士确认</Tag>}<div><strong>学习内容</strong><ul>{t.learn.map(x=><li key={x}>{x}</li>)}</ul></div><div className="topic-output"><strong>必须输出</strong><ul>{t.outputs.map(x=><li key={x}>{x}</li>)}</ul></div></Card>)}</div>
    <div className="learning-subhead"><span className="kicker">分阶段学习时间线</span><h3>客户行动决定学习节奏</h3></div><div className="learning-timeline">{learningTimeline.map(x=><Card key={x.period}><span>{x.period}</span><h4>{x.title}</h4><b>{x.hours}</b><p>{x.themes.join(' · ')}</p><strong>输出</strong><ul>{x.outputs.map(y=><li key={y}>{y}</li>)}</ul>{x.warning&&<div className="learning-warning">{x.warning}</div>}</Card>)}</div>
    <ResourceLibrary resources={resources} setResources={setResources}/>
    <div className="conversion-flow"><span>学习</span><i>→</i><span>总结</span><i>→</i><span>应用</span><i>→</i><span>观察结果</span><i>→</i><span>调整方法</span><i>→</i><span>固化为 SOP / 模板</span></div><div className="split learning-conversion"><Card><h3>每个模块必须回答</h3><ol>{['学到了什么？','哪部分与当前业务有关？','哪部分不适用于当前阶段？','准备改变哪个具体动作？','什么时候应用？','如何判断有效？','是否更新计划、SOP或模板？'].map(x=><li key={x}>{x}</li>)}</ol></Card><Card><h3>至少形成一种成果</h3><p>一个决策、流程、模板、检查清单、真实沟通改进、财务模型、客户实验，或一条明确不再继续做的事项。</p><div className="risk"><strong>禁止</strong><p>只记录大量摘抄而没有行动。</p></div></Card></div>
    <div className="learning-subhead"><span className="kicker">企业家思维与行为</span><h3>用可观察行为代替抽象口号</h3></div><div className="behavior-grid">{entrepreneurBehaviors.map((x,i)=><Card key={x.name}><span>{String(i+1).padStart(2,'0')}</span><h4>{x.name}</h4><p>{x.behavior}</p><div><strong>本周练习</strong>{x.practice}</div></Card>)}</div>
    <CapabilityDashboard reviews={reviews} setReviews={setReviews}/>
    <div className="learning-rhythm"><div><b>先找最短路径</b><span>能问客户、供应商或专家解决的问题，不先上完整课程。</span></div><div><b>每周一次小块学习</b><span>围绕当前唯一知识缺口，总投入不超过2小时。</span></div><div><b>学习硬约束</b><span>一份短总结、一项实际应用、一次效果观察；没有输出不算完成。</span></div><div><b>高强度客户周</b><span>课程可以暂停，只保留15—30分钟轻复盘，不补课。</span></div></div>
    <div className="notice legal">美国商业基础学习仅用于建立理解框架。具体法律、税务、移民和合规问题需由相关专业人士确认。</div>
  </>;
}
