import React, { useState } from 'react';
import { gates, templates } from '../data/planData';
import { exportData, importData, validateImport } from '../lib/workPlan';
import { Card, Modal, Tag } from './Common';

const weeklyBlank={week:'',coreResult:'',actions:['','',''],maintenance:'',productBlock:'',customerBlock:'',companyBlock:'',customerMetrics:'',financeMetrics:'',supported:'',rejected:'',risks:'',decision:'',nextFocus:''};
export function WeeklyWorkbench({reviews,setReviews}) {
  const [week,setWeek]=useState(()=>{const d=new Date();const monday=new Date(d);monday.setDate(d.getDate()-((d.getDay()+6)%7));return monday.toISOString().slice(0,10)});
  const data=reviews[week]||{...weeklyBlank,week,actions:['','','']};
  const set=(key,value)=>setReviews(v=>({...v,[week]:{...data,[key]:value,week,updatedAt:new Date().toISOString()}}));
  return <Card className="workbench-card"><div className="workbench-head"><div><span className="kicker">本地周度工作台</span><h3>一个结果，三项行动，20%缓冲</h3></div><label className="week-picker">本周开始<input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label></div><div className="review-grid"><label>本周唯一核心成果<textarea value={data.coreResult} onChange={e=>set('coreResult',e.target.value)}/></label><label>不超过五项维持任务<textarea value={data.maintenance} onChange={e=>set('maintenance',e.target.value)}/></label><fieldset><legend>三项关键行动</legend>{data.actions.map((x,i)=><input key={i} placeholder={`行动 ${i+1}`} value={x} onChange={e=>{const a=[...data.actions];a[i]=e.target.value;set('actions',a)}}/>)}</fieldset><fieldset><legend>周三障碍检查</legend><input placeholder="产品卡点" value={data.productBlock} onChange={e=>set('productBlock',e.target.value)}/><input placeholder="客户卡点" value={data.customerBlock} onChange={e=>set('customerBlock',e.target.value)}/><input placeholder="公司卡点" value={data.companyBlock} onChange={e=>set('companyBlock',e.target.value)}/></fieldset><label>客户数据<textarea value={data.customerMetrics} onChange={e=>set('customerMetrics',e.target.value)}/></label><label>财务数据<textarea value={data.financeMetrics} onChange={e=>set('financeMetrics',e.target.value)}/></label><label>被支持的假设<textarea value={data.supported} onChange={e=>set('supported',e.target.value)}/></label><label>被推翻的假设<textarea value={data.rejected} onChange={e=>set('rejected',e.target.value)}/></label><label>新风险<textarea value={data.risks} onChange={e=>set('risks',e.target.value)}/></label><label>本周决定<textarea value={data.decision} onChange={e=>set('decision',e.target.value)}/></label><label className="wide">下周重点<textarea value={data.nextFocus} onChange={e=>set('nextFocus',e.target.value)}/></label></div><p className="save-note">输入内容会自动保存在当前浏览器。</p></Card>;
}

const decisionBlank={originalGoal:'',actual:'',data:'',spend:'',findings:'',risks:'',unknowns:'',nextMoney:'',nextResult:'',decision:'',reason:'',nextDate:''};
export function DecisionGates({decisions,setDecisions,currentGate}) {
  const [editing,setEditing]=useState(null);
  const save=e=>{e.preventDefault();setDecisions(v=>({...v,[editing.id]:{...editing,updatedAt:new Date().toISOString()}}));setEditing(null)};
  return <div className="gate-grid">{gates.map((g,i)=>{const record=decisions[g.id],isNext=currentGate?.id===g.id;return <Card key={g.id} className={`gate-card ${isNext?'next':''}`}><div className="gate-top"><span>决策门 {i+1}</span>{record?.decision?<Tag tone={record.decision==='继续'?'green':record.decision==='暂停'?'red':'gold'}>{record.decision}</Tag>:isNext?<Tag tone="gold">最近决策门</Tag>:<Tag tone="muted">未决策</Tag>}</div><time>{g.displayDate||g.date}</time><h3>{g.title}</h3><ul>{g.criteria.map(x=><li key={x}>{x}</li>)}</ul><button className="secondary" onClick={()=>setEditing({id:g.id,...decisionBlank,...record})}>{record?'查看 / 更新记录':'填写决策记录'}</button></Card>})}
  {editing&&<Modal title={gates.find(g=>g.id===editing.id)?.title} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={save}>{[['originalGoal','原目标'],['actual','实际结果'],['data','关键数据'],['spend','本阶段支出'],['findings','新发现'],['risks','主要风险'],['unknowns','未验证假设'],['nextMoney','继续需要的资金'],['nextResult','下一阶段结果'],['reason','决定原因']].map(([key,label])=><label key={key}>{label}<textarea required value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></label>)}<label>结论*<select required value={editing.decision} onChange={e=>setEditing({...editing,decision:e.target.value})}><option value="">请选择</option><option>继续</option><option>调整</option><option>暂停</option></select></label><label>下一决策日期<input type="date" value={editing.nextDate} onChange={e=>setEditing({...editing,nextDate:e.target.value})}/></label><div className="form-actions full"><button type="button" onClick={()=>setEditing(null)}>取消</button><button className="primary">保存决策</button></div></form></Modal>}</div>;
}

export function TemplateCards({showToast,drafts,setDrafts}) {
  const [active,setActive]=useState(null);
  const value=(template,field)=>drafts[template.id]?.[field.id] ?? (field.type==='checklist'?{}:'');
  const update=(templateId,fieldId,next)=>setDrafts(v=>({...v,[templateId]:{...v[templateId],[fieldId]:next,updatedAt:new Date().toISOString()}}));
  const progress=t=>{const required=t.fields.filter(f=>f.required);if(!required.length)return 0;const filled=required.filter(f=>{const v=value(t,f);return f.type==='checklist'?Object.values(v).some(Boolean):String(v).trim()}).length;return Math.round(filled/required.length*100)};
  const selectOptions=f=>f.id==='effective'?['有效，保留','部分有效，调整','无效，放弃']:f.id==='start'?['开始','暂缓','不需要']:['继续','调整','暂停'];
  const format=t=>`${t.title}\n使用日期：${new Date().toLocaleDateString('zh-CN')}\n\n${t.fields.map(f=>{const v=value(t,f);if(f.type==='checklist'){const items=f.placeholder.split('\n');return `${f.label}\n${items.map((x,i)=>`${v[i]?'☑':'☐'} ${x}`).join('\n')}`}return `${f.label}\n${v||'TBD'}`}).join('\n\n')}`;
  const copyText=async(t)=>{const text=format(t);try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}showToast(`已复制已填写内容：${t.title}`)};
  const reset=t=>{if(!confirm(`清空“${t.title}”的本地草稿？`))return;setDrafts(v=>{const next={...v};delete next[t.id];return next});showToast('模板草稿已清空')};
  return <><div className="template-guide"><div><span className="kicker">从空白提纲升级为执行工具</span><h3>选择场景，填写，直接带走结果</h3></div><ol><li>按触发时机选择模板</li><li>站内填写并自动保存</li><li>复制结果到项目文件或邮件</li></ol></div><div className="template-grid">{templates.map(t=>{const pct=progress(t),filled=Object.keys(drafts[t.id]||{}).some(k=>k!=='updatedAt');return <Card key={t.id} className="template-card"><div className="template-card-top"><span className="kicker">{t.link}</span><span className="template-pct">{pct}%</span></div><h3>{t.title}</h3><dl><div><dt>何时使用</dt><dd>{t.when}</dd></div><div><dt>必须产出</dt><dd>{t.output}</dd></div></dl><div className="template-field-preview">{t.fields.slice(0,4).map(f=><span key={f.id}>{f.label}</span>)}<em>＋{t.fields.length-4}项</em></div><div className="template-actions"><button className="primary" onClick={()=>setActive(t)}>{filled?'继续填写':'开始填写'}</button>{filled&&<button className="secondary" onClick={()=>copyText(t)}>复制结果</button>}</div></Card>})}</div>
  {active&&<Modal title={active.title} onClose={()=>setActive(null)}><div className="template-modal-intro"><div><span>使用时机</span><strong>{active.when}</strong></div><div><span>完成产出</span><strong>{active.output}</strong></div></div><div className="template-progress"><span style={{width:`${progress(active)}%`}} /></div><form className="template-form" onSubmit={e=>{e.preventDefault();copyText(active)}}>{active.fields.map(f=><label key={f.id}>{f.label}{f.required&&<b>必填</b>}{f.type==='date'||f.type==='month'?<input type={f.type} value={value(active,f)} onChange={e=>update(active.id,f.id,e.target.value)}/>:f.type==='select'?<select value={value(active,f)} onChange={e=>update(active.id,f.id,e.target.value)}><option value="">请选择明确结论</option>{selectOptions(f).map(option=><option key={option}>{option}</option>)}</select>:f.type==='checklist'?<div className="template-checks">{f.placeholder.split('\n').map((item,i)=><label key={item}><input type="checkbox" checked={!!value(active,f)[i]} onChange={e=>update(active.id,f.id,{...value(active,f),[i]:e.target.checked})}/>{item}</label>)}</div>:<textarea rows="3" placeholder={f.placeholder} value={value(active,f)} onChange={e=>update(active.id,f.id,e.target.value)}/>}</label>)}<div className="template-form-actions"><button type="button" className="danger-outline" onClick={()=>reset(active)}>清空草稿</button><span>已自动保存到当前浏览器</span><button type="submit" className="primary">复制已填写结果</button></div></form></Modal>}</>;
}

export function BackupPanel({showToast}) {
  const [preview,setPreview]=useState(null);
  const download=()=>{const data=exportData(), blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`us-work-plan-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);showToast('完整备份已导出')};
  const read=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=validateImport(JSON.parse(reader.result));setPreview(data)}catch(err){showToast(err.message)}};reader.readAsText(file);e.target.value=''};
  const restore=()=>{if(!confirm('导入将覆盖当前浏览器中的工作台数据。继续吗？'))return;importData(preview);setPreview(null);location.reload()};
  return <Card className="backup-card"><div><span className="kicker">本地数据安全</span><h3>备份与迁移</h3><p>所有执行数据只保存在当前浏览器。建议每周导出一次 JSON 备份。</p></div><div className="backup-actions"><button className="secondary" onClick={download}>导出完整备份</button><label className="file-button">选择备份导入<input type="file" accept="application/json,.json" onChange={read}/></label></div>{preview&&<div className="import-preview"><strong>备份可用 · {new Date(preview.exportedAt).toLocaleString()}</strong><span>CRM {preview.data.crm.length} 家 · 费用 {preview.data.expenses.length} 笔</span><button className="primary" onClick={restore}>确认覆盖并导入</button><button onClick={()=>setPreview(null)}>取消</button></div>}</Card>;
}
